name:               "MIND Lab"
description:        "Methods for INcomplete Data (MIND)"


author:             "Tanya P. Garcia"
gravatar_hash:      "9179ca26a6ca8a926e65a0cbf31eb862"
github:             "Tanya-Garcia-Lab"

nav:
  - name:           "Welcome"
    href:           "/"
  - name:           "About"
    href:           "/about"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Research Lab"
    href:           "/research-team"
  - name:           "Lab News"
    href:           "/lab-news"
  - name:           "Joining the Lab"
    href:           "/research-requirements"
  - name:           "Funding"
    href:           "/funding"
  - name:           "CV"
    href:           "/images/Garcia_CV_8.pdf"
  - name:           "Coaching"
    href:           "/images/coaching-profiles.pdf"


paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown


defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


sass:
  style:            :compressed
  
      
gems:
  - jekyll-paginate
