name:               "Garcia Lab"
description:        "Garcia Lab"


author:             "Tanya P. Garcia"
gravatar_hash:      "9179ca26a6ca8a926e65a0cbf31eb862"
github:             "Tanya-Garcia-Lab"

nav:
  - name:           "Welcome"
    href:           "/"
  - name:           "About"
    href:           "/about"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Research Team"
    href:           "/research-team"
  - name:           "Joining the Team"
    href:           "/research-requirements"
  - name:           "CV"
    href:           <a href="/images/Garcia_CV_7.pdf" target="_blank"></a>



paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown


defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"


sass:
  style:            :compressed
  
      
gems:
  - jekyll-paginate
