name:               "Tanya P. Garcia"
description:        "Webpage for Tanya P. Garcia"

url:                "https://tpgarcia.github.io"
author:             "Tanya P. Garcia"
email:              "tpgarcia@stat.tamu.edu"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
email:              "tpgarcia@stat.tamu.edu"
github:             "tpgarcia"

disqus_shortname:   "tpgarcia"

background:         ""

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
