description:        "Tanya P. Garcia"

url:                "https://tpgarcia.github.io"
author:             "Tanya P. Garcia"
email:              "tpgarcia@stat.tamu.edu"
gravatar_hash:      "9179ca26a6ca8a926e65a0cbf31eb862"
email:              "tpgarcia@stat.tamu.edu"
github:             "tpgarcia"

disqus_shortname:   "tpgarcia"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           ""
  - name:           "Publications"
    href:           "/publications.html"
  - name:           "Funding"
    href:           "/funding.html"
  - name:           "Research Team"
    href:           "/research-team.html"
  - name:           "Joining the Team"
    href:           "/research-requirements.html"
  - name:           "Teaching"
    href:           "/teaching.html"
  - name:           "CV"
    href:           "images/Garcia_CV_5.pdf"


sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
