name:               "Garcia Research Group"

url:                "https://tpgarcia.github.io"
author:             "Tanya P. Garcia"
email:              "tpgarcia@stat.tamu.edu"
gravatar_hash:      "9179ca26a6ca8a926e65a0cbf31eb862"
nav:
  - name:           "Welcome"
    href:           "/"
  - name:           "About"
    href:           "/about"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Funding"
    href:           "/funding"
  - name:           "Research Team"
    href:           "/research-team"
  - name:           "Joining the Team"
    href:           "/research-requirements"
  - name:           "Teaching"
    href:           "/teaching"
  - name:           "CV"
    href:           "images/Garcia_CV_5.pdf"
email:              "tpgarcia@stat.tamu.edu"
github:             "tpgarcia"



background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown



sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
