name:               "Garcia Research Group"
description:        "Tanya P. Garcia's Research Group"

url:                "https://tpgarcia.github.io"
author:             "Tanya P. Garcia"
gravatar_hash:      "9179ca26a6ca8a926e65a0cbf31eb862"

sidebars:
- lb2_sidebar
- lb3_sidebar
- lb4_sidebar
- contrib_sidebar
- community_sidebar
- es_lb2_sidebar
- fr_lb2_sidebar
- ja_lb2_sidebar
- ko_lb3_sidebar
- ko_lb2_sidebar
- ru_lb2_sidebar
- zh_lb2_sidebar
- pt-br_lb2_sidebar

nav:
  - name:           "Welcome"
    href:           "/"
  - name:           "About"
    href:           "/about"
  - name:           "Publications"
    href:           "/publications"
  - name:           "Funding"
    href:           "/funding"
  - name:           "Research Team"
    href:           "/research-team"
  - name:           "Joining the Team"
    href:           "/research-requirements"
  - name:           "Teaching"
    href:           "/teaching"
  - name:           "CV"
    href:           "/images/Garcia_CV_5.pdf"
github:             "tpgarcia"



background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown



sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
